#ifndef ANL_H
#define ANL_H

#include "cellulargen.h"

#include "implicitautocorrect.h"
#include "implicitbasisfunction.h"
//#include "implicitbias.h"
#include "implicitblend.h"
#include "implicitbrightcontrast.h"
#include "implicitcache.h"
#include "implicitcellular.h"
#include "implicitclamp.h"
#include "implicitcombiner.h"
#include "implicitconstant.h"
//#include "implicitcos.h"
#include "implicitcurve.h"
#include "implicitextractrgbachannel.h"
//#include "implicitfloor.h"
#include "implicitfractal.h"
#include "implicitfunctiongradient.h"
//#include "implicitgain.h"
#include "implicitgradient.h"
#include "implicitmagnitude.h"
#include "implicitmath.h"
#include "implicitnormalizecoords.h"
//#include "implicitpow.h"
#include "implicitrgbadotproduct.h"
#include "implicitrotatedomain.h"
#include "implicitsawtooth.h"
#include "implicitscaledomain.h"
#include "implicitscaleoffset.h"
#include "implicitselect.h"
//#include "implicitsin.h"
#include "implicitsphere.h"
#include "implicittiers.h"
#include "implicittranslatedomain.h"
#include "implicittriangle.h"

#include "rgbablend.h"
#include "rgbablendops.h"
#include "rgbacolorops.h"
#include "rgbaconstant.h"
#include "rgbacomposechannels.h"
#include "rgbacurve.h"
#include "rgbahsvtorgba.h"
#include "rgbaimplicitgrayscale.h"
#include "rgbanormalize.h"
#include "rgbargbatohsv.h"
#include "rgbarotatecolor.h"
#include "rgbaselect.h"

#include "random_gen.h"
#include "mapping.h"
#include "arrayoperations.h"

#include "vectortypes.h"

#include "implicitbufferbase.h"
#include "implicitbufferimplicitadapter.h"
#include "implicitbufferblur.h"
#include "implicitbufferscaletorange.h"
#include "implicitbufferbumpmap.h"
#include "implicitbufferunarymath.h"
#include "implicitbuffersimpleerode.h"

#include "rgbabufferrgbaadapter.h"
#include "rgbabufferimplicitbufferadapter.h"
#include "rgbabufferblur.h"
#include "rgbabufferimplicitbuffermultiply.h"

#endif

